---
- name: Configure AAP - full CaC apply
  hosts: localhost
  gather_facts: false
  connection: local

  vars_files:
    - CaC/credentials.yaml
    - CaC/job_templates.yml
  pre_tasks:
    - name: debug variables
      ansible.builtin.debug:
        var: controller_templates
    - name: debug variables
      ansible.builtin.debug:
        var: controller_credentials
  roles:
    - infra.aap_configuration.controller_credentials
    - infra.aap_configuration.controller_job_templates